export enum organizations {
  CAN_VIEW_ORGANIZATION = "CAN_VIEW_ORGANIZATION",
  CAN_CREATE_ORGANIZATION = "CAN_CREATE_ORGANIZATION",
  CAN_UPDATE_ORGANIZATION = "CAN_UPDATE_ORGANIZATION",
  CAN_DELETE_ORGANIZATION = "CAN_DELETE_ORGANIZATION",
  CAN_VIEW_ALL_ORGANIZATIONS = "CAN_VIEW_ALL_ORGANIZATIONS",
}

export enum members {
  CAN_VIEW_ALL_MEMBERS = "CAN_VIEW_ALL_MEMBERS",
  CAN_VIEW_ORGANIZATION_MEMBERS = "CAN_VIEW_ORGANIZATION_MEMBERS",
  CAN_CREATE_MEMBER = "CAN_CREATE_MEMBER",
  CAN_UPDATE_MEMBER = "CAN_UPDATE_MEMBER",
  CAN_DELETE_MEMBER = "CAN_DELETE_MEMBER",
  CAN_UPDATE_ANY_MEMBER = "CAN_UPDATE_ANY_MEMBER",
  CAN_DELETE_ANY_MEMBER = "CAN_DELETE_ANY_MEMBER",
}

export enum users {
  CAN_VIEW_ALL_USERS = "CAN_VIEW_ALL_USERS",
  CAN_VIEW_USER = "CAN_VIEW_USER",
  CAN_CREATE_USER = "CAN_CREATE_USER",
  CAN_UPDATE_USER = "CAN_UPDATE_USER",
  CAN_DELETE_USER = "CAN_DELETE_USER",
  CAN_UPDATE_ANY_USER = "CAN_UPDATE_ANY_USER",
  CAN_DELETE_ANY_USER = "CAN_DELETE_ANY_USER",
}

export enum organizationCategories {
  CAN_VIEW_ORGANIZATION_CATEGORIES = "CAN_VIEW_ORGANIZATION_CATEGORIES",
  CAN_CREATE_ORGANIZATION_CATEGORIES = "CAN_CREATE_ORGANIZATION_CATEGORIES",
  CAN_UPDATE_ORGANIZATION_CATEGORIES = "CAN_UPDATE_ORGANIZATION_CATEGORIES",
  CAN_DELETE_ORGANIZATION_CATEGORIES = "CAN_DELETE_ORGANIZATION_CATEGORIES",
}

export enum organizationServices {
  CAN_VIEW_ORGANIZATION_SERVICES = "CAN_VIEW_ORGANIZATION_SERVICES",
  CAN_CREATE_ORGANIZATION_SERVICES = "CAN_CREATE_ORGANIZATION_SERVICES",
  CAN_UPDATE_ORGANIZATION_SERVICES = "CAN_UPDATE_ORGANIZATION_SERVICES",
  CAN_DELETE_ORGANIZATION_SERVICES = "CAN_DELETE_ORGANIZATION_SERVICES",
  CAN_VIEW_ALL_ORGANIZATION_SERVICES = "CAN_VIEW_ALL_ORGANIZATION_SERVICES",
  CAN_VIEW_ORGANIZATION_SERVICE = "CAN_VIEW_ORGANIZATION_SERVICE",
}

export enum services {
  CAN_VIEW_SERVICES = "CAN_VIEW_SERVICES",
  CAN_CREATE_SERVICES = "CAN_CREATE_SERVICES",
  CAN_UPDATE_SERVICES = "CAN_UPDATE_SERVICES",
  CAN_DELETE_SERVICES = "CAN_DELETE_SERVICES",
}

export enum serviceCategories {
  CAN_VIEW_SERVICE_CATEGORIES = "CAN_VIEW_SERVICE_CATEGORIES",
  CAN_CREATE_SERVICE_CATEGORIES = "CAN_CREATE_SERVICE_CATEGORIES",
  CAN_UPDATE_SERVICE_CATEGORIES = "CAN_UPDATE_SERVICE_CATEGORIES",
  CAN_DELETE_SERVICE_CATEGORIES = "CAN_DELETE_SERVICE_CATEGORIES",
  CAN_VIEW_SERVICE_TYPES = "CAN_VIEW_SERVICE_TYPES",
  CAN_CREATE_SERVICE_TYPES = "CAN_CREATE_SERVICE_TYPES",
}

export enum organizationRoles {
  CAN_VIEW_ORGANIZATION_ROLES = "CAN_VIEW_ORGANIZATION_ROLES",
  CAN_CREATE_ORGANIZATION_ROLES = "CAN_CREATE_ORGANIZATION_ROLES",
  CAN_UPDATE_ORGANIZATION_ROLES = "CAN_UPDATE_ORGANIZATION_ROLES",
  CAN_DELETE_ORGANIZATION_ROLES = "CAN_DELETE_ORGANIZATION_ROLES",
}

export enum memberRoles {
  CAN_VIEW_MEMBER_ROLES = "CAN_VIEW_MEMBER_ROLES",
  CAN_CREATE_MEMBER_ROLES = "CAN_CREATE_MEMBER_ROLES",
  CAN_UPDATE_MEMBER_ROLES = "CAN_UPDATE_MEMBER_ROLES",
  CAN_DELETE_MEMBER_ROLES = "CAN_DELETE_MEMBER_ROLES",
  CAN_VIEW_MEMBER_STATISTICS = "CAN_VIEW_MEMBER_STATISTICS",
}

export enum organizationServices {
  CAN_ASSIGN_SERVICE_TO_AN_ORGANIZATION = "CAN_ASSIGN_SERVICE_TO_AN_ORGANIZATION",
  CAN_VIEW_ALL_OFFERED_SERVICES = "CAN_VIEW_ALL_OFFERED_SERVICES",
  CAN_VIEW_OFFERED_SERVICE = "CAN_VIEW_OFFERED_SERVICE",
  CAN_UPDATE_OFFERED_SERVICE = "CAN_UPDATE_OFFERED_SERVICE",
  CAN_DELETE_OFFERED_SERVICE = "CAN_DELETE_OFFERED_SERVICE",
}

export enum memberServices {
  CAN_VIEW_MEMBER_SERVICES = "CAN_VIEW_MEMBER_SERVICES",
  CAN_ASSIGN_SERVICE_TO_A_MEMBER = "CAN_ASSIGN_SERVICE_TO_A_MEMBER",
  CAN_UPDATE_MEMBER_SERVICE = "CAN_UPDATE_MEMBER_SERVICE",
  CAN_DELETE_MEMBER_SERVICE = "CAN_DELETE_MEMBER_SERVICE",
}

export enum serviceTransactions {
  CAN_VIEW_SERVICE_TRANSACTIONS = "CAN_VIEW_SERVICE_TRANSACTIONS",
}

// Types for enum values
export type OrganizationPermission = `${organizations}`;
export type MemberPermission = `${members}`;
export type UserPermission = `${users}`;
export type OrganizationCategoryPermission = `${organizationCategories}`;
export type OrganizationServicePermission = `${organizationServices}`;
export type OrganizationRolePermission = `${organizationRoles}`;
export type MemberRolePermission = `${memberRoles}`;
export type ServiceCategoryPermission = `${serviceCategories}`;
export type MemberServicePermission = `${memberServices}`;
export type ServiceTransactionPermission = `${serviceTransactions}`;
export type ServicePermission = `${services}`;

// Combined permission type
export type Permission =
  | OrganizationPermission
  | MemberPermission
  | UserPermission
  | OrganizationCategoryPermission
  | OrganizationServicePermission
  | OrganizationRolePermission
  | MemberRolePermission
  | ServiceCategoryPermission
  | MemberServicePermission
  | ServiceTransactionPermission
  | ServicePermission;

// You can also create a type for each specific resource and action
export type PermissionResource =
  | "organizations"
  | "members"
  | "users"
  | "organizationCategories"
  | "organizationServices"
  | "serviceCategories"
  | "memberServices"
  | "serviceTransactions"
  | "services";
